# Generated by Django 4.1.5 on 2023-02-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=32)),
                ('email', models.CharField(max_length=250)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('groupe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ClassroomApp.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, choices=[('Haricot', 'Haricot'), ('Riz', 'Riz'), ('Pâtes', 'Pâtes'), ('Soupe', 'Soupe'), ('Aucun', 'Aucun')], default='', max_length=200)),
                ('quantite', models.IntegerField(default=0)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClassroomApp.etudiant')),
                ('groupe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ClassroomApp.groupe')),
            ],
        ),
    ]
