# Generated by Django 4.1.5 on 2023-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassroomApp', '0002_alter_etudiant_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/photo'),
        ),
    ]
